version: '3.8'
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    command: redis-server --requirepass antifraud123

  api-gateway:
    build: ./services/api-gateway
    ports: ["8080:8080"]
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - CIRCUIT_BREAKER_ENABLED=true
      - AUTH_SERVICE_URL=http://auth-service:3001
      - LINK_SERVICE_URL=http://link-service:3002
      - COMMUNITY_SERVICE_URL=http://community-service:3003
      - CHAT_SERVICE_URL=http://chat-service:3004
      - NEWS_SERVICE_URL=http://news-service:3005
      - ADMIN_SERVICE_URL=http://admin-service:3006
    depends_on: [redis, auth-service, link-service, community-service]

  auth-service:
    build: ./services/auth-service
    ports: ["3001:3001"]
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - EVENT_BUS_ENABLED=true
    depends_on: [redis]
  
  prometheus:
    image: prom/prometheus
    ports: ["9090:9090"]
  
  grafana:
    image: grafana/grafana
    ports: ["3010:3000"]
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

  link-service:
    build: ./services/link-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - EVENT_BUS_ENABLED=true
    depends_on:
      - redis

  community-service:
    build: ./services/community-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
      - EVENT_BUS_ENABLED=true
    depends_on:
      - redis

  chat-service:
    build: ./services/chat-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  news-service:
    build: ./services/news-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

  admin-service:
    build: ./services/admin-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis