version: '3.8'

services:
  # Hadoop NameNode
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: factcheck-namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=factcheck-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - .env
    networks:
      - factcheck-bigdata

  # Hadoop DataNode
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: factcheck-datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - .env
    depends_on:
      - namenode
    networks:
      - factcheck-bigdata

  # Spark Master
  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: factcheck-spark-master
    restart: always
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - ./services/spark-service/jobs:/opt/spark-jobs
      - ./services/spark-service/data:/opt/spark-data
    networks:
      - factcheck-bigdata

  # Spark Worker 1
  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: factcheck-spark-worker-1
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
    volumes:
      - ./services/spark-service/jobs:/opt/spark-jobs
      - ./services/spark-service/data:/opt/spark-data
    depends_on:
      - spark-master
    networks:
      - factcheck-bigdata

  # Spark Worker 2
  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: factcheck-spark-worker-2
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_PORT=8882
      - SPARK_WORKER_WEBUI_PORT=8082
    volumes:
      - ./services/spark-service/jobs:/opt/spark-jobs
      - ./services/spark-service/data:/opt/spark-data
    depends_on:
      - spark-master
    networks:
      - factcheck-bigdata

  # Jupyter Notebook for Spark Development
  jupyter-spark:
    image: jupyter/pyspark-notebook:spark-3.3.0
    container_name: factcheck-jupyter-spark
    restart: always
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - ./services/spark-service/notebooks:/home/jovyan/work
      - ./services/spark-service/data:/home/jovyan/data
    depends_on:
      - spark-master
    networks:
      - factcheck-bigdata

  # Zeppelin for Spark Analytics (Alternative to Jupyter)
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: factcheck-zeppelin
    restart: always
    ports:
      - "8890:8080"
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - ZEPPELIN_ADDR=0.0.0.0
    volumes:
      - ./services/spark-service/notebooks:/opt/zeppelin/notebook
      - ./services/spark-service/data:/opt/zeppelin/data
    depends_on:
      - spark-master
    networks:
      - factcheck-bigdata

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  factcheck-bigdata:
    driver: bridge
    external: false
