version: '3.8'

services:
  # Hadoop NameNode
  hadoop-namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: factcheck-hadoop-namenode
    hostname: namenode
    ports:
      - "9870:9870"  # NameNode Web UI
      - "9000:9000"  # HDFS
    environment:
      - CLUSTER_NAME=factcheck-cluster
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false
    volumes:
      - hadoop-namenode:/hadoop/dfs/name
      - ./config/hadoop:/opt/hadoop/etc/hadoop
    networks:
      - factcheck-network
    restart: unless-stopped

  # Hadoop DataNode
  hadoop-datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: factcheck-hadoop-datanode
    hostname: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - CORE_CONF_hadoop_http_staticuser_user=root
      - CORE_CONF_hadoop_proxyuser_hue_hosts=*
      - CORE_CONF_hadoop_proxyuser_hue_groups=*
      - CORE_CONF_io_compression_codecs=org.apache.hadoop.io.compress.SnappyCodec
      - HDFS_CONF_dfs_webhdfs_enabled=true
      - HDFS_CONF_dfs_permissions_enabled=false
      - HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check=false
    volumes:
      - hadoop-datanode:/hadoop/dfs/data
      - ./config/hadoop:/opt/hadoop/etc/hadoop
    networks:
      - factcheck-network
    depends_on:
      - hadoop-namenode
    restart: unless-stopped

  # Spark Master
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: factcheck-spark-master
    hostname: spark-master
    ports:
      - "8088:8080"  # Spark Master Web UI
      - "7077:7077"  # Spark Master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark-master:/opt/bitnami/spark
      - ./config/spark:/opt/bitnami/spark/conf
    networks:
      - factcheck-network
    restart: unless-stopped

  # Spark Worker 1
  spark-worker-1:
    image: bitnami/spark:3.4.1
    container_name: factcheck-spark-worker-1
    hostname: spark-worker-1
    ports:
      - "8081:8081"  # Spark Worker 1 Web UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark-worker-1:/opt/bitnami/spark
      - ./config/spark:/opt/bitnami/spark/conf
    networks:
      - factcheck-network
    depends_on:
      - spark-master
    restart: unless-stopped

  # Spark Worker 2
  spark-worker-2:
    image: bitnami/spark:3.4.1
    container_name: factcheck-spark-worker-2
    hostname: spark-worker-2
    ports:
      - "8082:8081"  # Spark Worker 2 Web UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark-worker-2:/opt/bitnami/spark
      - ./config/spark:/opt/bitnami/spark/conf
    networks:
      - factcheck-network
    depends_on:
      - spark-master
    restart: unless-stopped

  # Jupyter Spark
  jupyter-spark:
    image: jupyter/pyspark-notebook:latest
    container_name: factcheck-jupyter-spark
    hostname: jupyter-spark
    ports:
      - "8888:8888"  # Jupyter Notebook
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - SPARK_OPTS="--driver-java-options=-Xms1024M --driver-java-options=-Xmx4096M --driver-java-options=-Dlog4j.logLevel=org.apache.spark=WARN"
    volumes:
      - jupyter-data:/home/jovyan/work
      - ./notebooks:/home/jovyan/work/notebooks
    networks:
      - factcheck-network
    depends_on:
      - spark-master
      - hadoop-namenode
    restart: unless-stopped

  # Zeppelin
  zeppelin:
    image: apache/zeppelin:0.10.1
    container_name: factcheck-zeppelin
    hostname: zeppelin
    ports:
      - "8890:8080"  # Zeppelin Web UI
    environment:
      - ZEPPELIN_SERVER_PORT=8080
      - SPARK_HOME=/opt/bitnami/spark
    volumes:
      - zeppelin-data:/zeppelin/notebook
      - zeppelin-conf:/zeppelin/conf
    networks:
      - factcheck-network
    depends_on:
      - spark-master
    restart: unless-stopped

volumes:
  hadoop-namenode:
    driver: local
  hadoop-datanode:
    driver: local
  spark-master:
    driver: local
  spark-worker-1:
    driver: local
  spark-worker-2:
    driver: local
  jupyter-data:
    driver: local
  zeppelin-data:
    driver: local
  zeppelin-conf:
    driver: local

networks:
  factcheck-network:
    external: true 