version: '3.8'

services:
  # =============================================================================
  # REDIS - Event Pub/Sub and Caching
  # =============================================================================
  redis:
    image: redis:7-alpine
    container_name: factcheck-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: >
      redis-server 
      --appendonly yes 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru
      --requirepass antifraud123
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "antifraud123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - factcheck-network
    environment:
      - REDIS_PASSWORD=antifraud123

  # =============================================================================
  # RABBITMQ - Message Queue and Reliable Messaging
  # =============================================================================
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: factcheck-rabbitmq
    ports:
      - "5672:5672"    # AMQP port
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: factcheck
      RABBITMQ_DEFAULT_PASS: secure_password
      RABBITMQ_DEFAULT_VHOST: /
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit log_levels [{connection,error},{default,info}]
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - rabbitmq-logs:/var/log/rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - factcheck-network

  # =============================================================================
  # EVENTSTORE (Optional) - Event Sourcing Database
  # =============================================================================
  eventstore:
    image: eventstore/eventstore:23.10.0-bookworm-slim
    container_name: factcheck-eventstore
    ports:
      - "2113:2113"  # HTTP API
      - "1113:1113"  # TCP
    environment:
      EVENTSTORE_CLUSTER_SIZE: 1
      EVENTSTORE_RUN_PROJECTIONS: All
      EVENTSTORE_START_STANDARD_PROJECTIONS: true
      EVENTSTORE_EXT_TCP_PORT: 1113
      EVENTSTORE_HTTP_PORT: 2113
      EVENTSTORE_INSECURE: true
      EVENTSTORE_ENABLE_EXTERNAL_TCP: true
      EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP: true
      EVENTSTORE_MEM_DB: true
    volumes:
      - eventstore-data:/var/lib/eventstore
      - eventstore-logs:/var/log/eventstore
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2113/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - factcheck-network
    profiles:
      - full  # Only start with --profile full

# =============================================================================
# VOLUMES
# =============================================================================
volumes:
  redis-data:
    driver: local
  rabbitmq-data:
    driver: local
  rabbitmq-logs:
    driver: local
  eventstore-data:
    driver: local
  eventstore-logs:
    driver: local

# =============================================================================
# NETWORKS
# =============================================================================
networks:
  factcheck-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
