services:
  # Frontend - React App
  - type: web
    name: factcheck-frontend
    env: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://factcheck-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend - Express API Server
  - type: web
    name: factcheck-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm ci
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://factcheck-frontend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: factcheck-db
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: factcheck-1d6e8
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false

# Database - PostgreSQL
databases:
  - name: factcheck-db
    databaseName: factcheck
    user: factcheck_user
    region: singapore
    plan: free
