{
  "services": [
    {
      "type": "web",
      "name": "factcheck-auth-service",
      "env": "docker",
      "dockerfilePath": "./services/auth-service/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "web",
      "name": "factcheck-link-service",
      "env": "docker",
      "dockerfilePath": "./services/link-service/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "web",
      "name": "factcheck-community-service",
      "env": "docker",
      "dockerfilePath": "./services/community-service/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "web",
      "name": "factcheck-chat-service",
      "env": "docker",
      "dockerfilePath": "./services/chat-service/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "web",
      "name": "factcheck-news-service",
      "env": "docker",
      "dockerfilePath": "./services/news-service/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "web",
      "name": "factcheck-admin-service",
      "env": "docker",
      "dockerfilePath": "./services/admin-service/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "web",
      "name": "factcheck-phishtank-service",
      "env": "docker",
      "dockerfilePath": "./services/phishtank-service/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "web",
      "name": "factcheck-criminalip-service",
      "env": "docker",
      "dockerfilePath": "./services/criminalip-service/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "web",
      "name": "factcheck-api-gateway",
      "env": "docker",
      "dockerfilePath": "./services/api-gateway/Dockerfile.render",
      "dockerContext": ".",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "healthCheckPath": "/health",
      "envVars": [
        {
          "key": "NODE_ENV",
          "value": "production"
        },
        {
          "key": "PORT",
          "value": "10000"
        }
      ]
    },
    {
      "type": "static",
      "name": "factcheck-frontend",
      "buildCommand": "cd client && npm ci && npm run build",
      "staticPublishPath": "./client/build",
      "repo": "https://github.com/VinkRasengan/backup",
      "branch": "main",
      "envVars": [
        {
          "key": "REACT_APP_API_URL",
          "value": "https://backup-zhhs.onrender.com"
        },
        {
          "key": "GENERATE_SOURCEMAP",
          "value": "false"
        }
      ]
    }
  ]
}