services:
  # Frontend - React App
  - type: web
    name: factcheck-frontend
    env: static
    buildCommand: cd client && npm ci && npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: https://factcheck-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend - Express API Server
  - type: web
    name: factcheck-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install --production
    startCommand: cd server && npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://factcheck-frontend.onrender.com
      - key: USE_FIRESTORE
        value: true
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_URL
        value: https://api.openai.com/v1
      - key: OPENAI_MODEL
        value: gpt-3.5-turbo
      - key: OPENAI_MAX_TOKENS
        value: 500
      - key: OPENAI_TEMPERATURE
        value: 0.7
      - key: VIRUSTOTAL_API_KEY
        sync: false
      - key: NEWSAPI_KEY
        sync: false
      - key: NEWSDATA_API_KEY
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: factcheck-1d6e8
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: VIRUSTOTAL_API_URL
        value: https://www.virustotal.com/api/v3
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100

# NO DATABASE SECTION - Using Firestore only
