version: 2.1

executors:
  node-executor:
    docker:
      - image: cimg/node:20.11
    working_directory: ~/repo

commands:
  install_deps:
    description: "Install dependencies"
    parameters:
      path:
        type: string
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd << parameters.path >>
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi

  # run_tests:
  #   description: "Run tests"
  #   parameters:
  #     path:
  #       type: string
  #   steps:
  #     - run:
  #         name: Run tests
  #         command: |
  #           cd << parameters.path >>
  #           npm test

jobs:
  test_auth_service:
    executor: node-executor
    context: factcheck-auth
    steps:
      - install_deps:
          path: services/auth-service
      # - run_tests:
      #     path: services/auth-service

  test_link_service:
    executor: node-executor
    context: factcheck-link
    steps:
      - install_deps:
          path: services/link-service
      # - run_tests:
      #     path: services/link-service

  test_community_service:
    executor: node-executor
    context: factcheck-community
    steps:
      - install_deps:
          path: services/community-service
      # - run_tests:
      #     path: services/community-service

  test_chat_service:
    executor: node-executor
    context: factcheck-chat
    steps:
      - install_deps:
          path: services/chat-service
      # - run_tests:
      #     path: services/chat-service

  test_news_service:
    executor: node-executor
    context: factcheck-news
    steps:
      - install_deps:
          path: services/news-service
      # - run_tests:
      #     path: services/news-service

  test_admin_service:
    executor: node-executor
    context: factcheck-admin
    steps:
      - install_deps:
          path: services/admin-service
      # - run_tests:
      #     path: services/admin-service

  test_phishtank_service:
    executor: node-executor
    context: factcheck-phishtank
    steps:
      - install_deps:
          path: services/phishtank-service
      # - run_tests:
      #     path: services/phishtank-service

  test_criminalip_service:
    executor: node-executor
    context: factcheck-criminalip
    steps:
      - install_deps:
          path: services/criminalip-service
      # - run_tests:
      #     path: services/criminalip-service

  test_api_gateway:
    executor: node-executor
    context: factcheck-api-gateway
    steps:
      - install_deps:
          path: services/api-gateway
      # - run_tests:
      #     path: services/api-gateway

  test_frontend:
    executor: node-executor
    context: factcheck-frontend
    steps:
      - install_deps:
          path: client
      # - run:
      #     name: Run frontend tests
      #     command: |
      #       cd client
      #       npm test -- --watchAll=false

workflows:
  version: 2
  ci:
    jobs:
      - test_auth_service
      - test_link_service
      - test_community_service
      - test_chat_service
      - test_news_service
      - test_admin_service
      - test_phishtank_service
      - test_criminalip_service
      - test_api_gateway
      - test_frontend