global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'link-service'
    static_configs:
      - targets: ['link-service:3002']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'community-service'
    static_configs:
      - targets: ['community-service:3003']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:3004']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'news-service'
    static_configs:
      - targets: ['news-service:3005']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'admin-service'
    static_configs:
      - targets: ['admin-service:3006']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s